services:
  mysql:
    image: mysql:8.0
    container_name: healthcare-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: healthcare_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: